library(MatchIt)
conflicts_match <- read.csv("matching_fin050723.csv")
conflicts_main <- read.csv("c_main.csv")
rownames(conflicts_match) <- conflicts_match$id_unique
conflicts_match[is.na(conflicts_match)] <- 0
conflicts_match$drugs = conflicts_match$opium & conflicts_match$cannabis & conflicts_match$coca_production

#m.out <- matchit(Non_intervention ~ conflict_duration_guess + conflict_type_intra + conflict_type_extra + conflict_type_inter + conflict_type_non + conflict_type_minor + cause_political + cause_separatism + cause_ethnic + cause_religious + cause_international + cause_crime + cause_complex + land_locked + deaths_initial + death_mean + death_max + EFindex + mountains_mean + diamprim_s + polity + milex + Sapphire + Emerald + Aquamarine + Heliodor + Moganite + Goshenite + Nephrite + Jadeite + Lapis.Lazuli + Opal + Tourmaline + Periodit + Topaz + Pearl + Garnet + Zircon + Spinel + Amber + Quarz + diamond + gdppc + pop + number_sides + sanctions + terror_bomb + opium + cannabis + coca_production + Africa + Americas + Asia + Europe + Oceania + Central.Asia + Eastern.Asia + Eastern.Europe + Latin.America.and.the.Caribbean + Melanesia + Northern.Africa + Northern.America + Northern.Europe + South.eastern.Asia + Southern.Asia + Southern.Europe + Sub.Saharan.Africa + Western.Asia + ColRuler_200 + ColRuler_210 + ColRuler_211 + ColRuler_220 + ColRuler_230 + ColRuler_235 + ColRuler_300 + ColRuler_325 + ColRuler_365 + ColRuler_640, data = conflicts_match, method="genetic", replace=TRUE, pop.size=500)
#m.out <- matchit(Non_intervention ~ conflict_duration_guess + conflict_type_intra + conflict_type_extra + conflict_type_inter + conflict_type_non + conflict_type_minor + cause_political + cause_separatism + cause_ethnic + cause_religious + cause_international + cause_crime + cause_complex + land_locked + deaths_initial + death_mean + death_max + EFindex + mountains_mean + diamprim_s + polity + milex + diamond + gdppc + pop + number_sides + sanctions + terror_bomb + drugs + Africa + Americas + Asia + Europe + Oceania + Central.Asia + Eastern.Asia + Eastern.Europe + Latin.America.and.the.Caribbean + Melanesia + Northern.Africa + Northern.America + Northern.Europe + South.eastern.Asia + Southern.Asia + Southern.Europe + Sub.Saharan.Africa + Western.Asia + ColRuler_200 + ColRuler_210 + ColRuler_211 + ColRuler_220 + ColRuler_230 + ColRuler_235 + ColRuler_300 + ColRuler_325 + ColRuler_365 + ColRuler_640, data = conflicts_match, method="genetic", replace=TRUE, pop.size=500)
#m.out <- matchit(Non_intervention ~ conflict_duration_guess + conflict_type_intra + conflict_type_extra + conflict_type_inter + conflict_type_non + conflict_type_minor + cause_political + cause_separatism + cause_ethnic + cause_religious + cause_international + cause_crime + cause_complex + land_locked + deaths_initial + death_mean + death_max + EFindex + mountains_mean + diamprim_s + polity + milex + diamond + gdppc + pop + number_sides + sanctions + terror_bomb + drugs + Africa + Americas + Asia + Europe + Oceania + Central.Asia + Eastern.Asia + Eastern.Europe + Latin.America.and.the.Caribbean + Melanesia + Northern.Africa + Northern.America + Northern.Europe + South.eastern.Asia + Southern.Asia + Southern.Europe + Sub.Saharan.Africa + Western.Asia + ColRuler_200 + ColRuler_210 + ColRuler_211 + ColRuler_220 + ColRuler_230 + ColRuler_235 + ColRuler_300 + ColRuler_325 + ColRuler_365 + ColRuler_640, data = conflicts_match, method="genetic", replace=TRUE, pop.size=500, discard=(conflicts_match$Peacekeeping==1))
m.out <- matchit(Non_intervention ~ conflict_type_intra + conflict_type_extra + conflict_type_inter + conflict_type_non + conflict_type_minor + cause_political + cause_separatism + cause_ethnic + cause_religious + cause_international + cause_crime + cause_complex + land_locked + deaths_initial + EFindex + mountains_mean + diamprim_s + polity + milex + diamond + gdppc + pop + number_sides + sanctions + terror_bomb + drugs + Africa + Americas + Asia + Europe + Oceania + Central.Asia + Eastern.Asia + Eastern.Europe + Latin.America.and.the.Caribbean + Melanesia + Northern.Africa + Northern.America + Northern.Europe + South.eastern.Asia + Southern.Asia + Southern.Europe + Sub.Saharan.Africa + Western.Asia + ColRuler_200 + ColRuler_210 + ColRuler_211 + ColRuler_220 + ColRuler_230 + ColRuler_235 + ColRuler_300 + ColRuler_325 + ColRuler_365 + ColRuler_640, data = conflicts_match, method="genetic", replace=TRUE, pop.size=500, discard=(conflicts_match$Peacekeeping==1 | conflicts_match$invalidate==1))
#m.out[["match.matrix"]]
#summary(m.out)

res = m.out[["match.matrix"]]
control <- attributes(res)$dimnames[1][[1]]
treatment <- as.list(res)
res_df <- do.call(rbind, Map(data.frame, A=control, B=treatment))
res_fin <- merge(res_df, conflicts_match[c('id_unique', 'conflict_name_ru')], by.x = "A", by.y = "id_unique")
names(res_fin)[names(res_fin) == 'conflict_name_ru'] <- 'conflict_name_A'
res_fin <- merge(res_fin, conflicts_match[c('id_unique', 'conflict_name_ru')], by.x = "B", by.y = "id_unique")
names(res_fin)[names(res_fin) == 'conflict_name_ru'] <- 'conflict_name_B'
res_fin <- merge(res_fin, conflicts_main[c('conflict_name_ru', 'intruders_new', 'intruders_new_auspecies')], by.x = "conflict_name_B", by.y = "conflict_name_ru", all.x=TRUE)
write.csv(res_fin, file = "matching_res_fin.csv", fileEncoding = "UTF-8")

